### ISSUE TITLE
Access token leaked on header when request to Spotify

### ISSUE THREAD

**Issue by XiaoXuxxxx** [riflowth/share-me-some-song#1]
Every time when the user type the keyword, the search request will sent directly to the Spotify. And access token will leaked via the header. In my opinion, the search request should be sent to your server and your server send it again to Spotify to prevent token leaked.

**Comment by riflowth** [comment]
Oh, this is my mistake. I will fix it asap.
Thanks @XiaoXuxxxx

**Comment by riflowth** [comment]
fix on PR #2
Thanks @XiaoXuxxxx again for this ticket
